server:
  port: 8080 # ?????????????????????8080
  servlet:
    context-path: /api # ?????????????????????????? /api/user

spring:
  application:
    name: drg-springboot # ???????Spring Boot????????????????
  datasource:
    url: jdbc:mysql://localhost:3308/resume_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root # ??????
    password: mysql8 # ?????
    driver-class-name: com.mysql.cj.jdbc.Driver # ???JDBC????
#    hikari: # HikariCP????????
#      maximum-pool-size: 10 # ?????????
#      minimum-idle: 5 # ???????????
#      idle-timeout: 30000 # ??????????????????
#      max-lifetime: 1800000 # ?????????????????
#      connection-timeout: 30000 # ??????????????????

mybatis-plus: # MyBatis Plus???
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # ??SQL??????
    map-underscore-to-camel-case: true # ????????????
    aggressive-lazy-loading: false # ????????????N+1?????
  mapper-locations: classpath:mapper/*.xml # MyBatis???????
  global-config:
    banner: false # ??Spring Boot?????
    db-config:
      id-type: auto # ???ID??????????

file: # ?????????
  upload-dir: ./uploads/ # ????????
  export-dir: ./exports/ # ????????

security: # ????
  jwt: # JWT?JSON Web Token???
    secret: qyun_secret_key # JWT???????????
    expiration: 86400000 # JWT????????????86400000???1??
  user: # ??????
    password: admin123 # ???????

logging: # ????
  level:
    root: info # ????????info
    org.springframework.web: debug # ??Spring Web????????debug??????????
    com.qyun: debug # ???????????debug????????????

management: # ?????
  endpoints:
    web:
      exposure:
        include: "*" # ??????????/actuator/health?/actuator/metrics????
  endpoint:
    health:
      show-details: always # ????????????????????????

# ??????
custom: # ???????
  file:
    supported-formats: pdf,word,html # ?????????
  resume:
    templates-dir: ./templates/ # ????????
  admin:
    default-email: admin@example.com # ???????
